Repo for ticket 61039 - using a different fork as initial skeleton

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,47 +1,52 @@
 version: 2
 jobs:
   build:
-    docker:
+    machine:
+      image: ubuntu-1604:201903-01    # pins image to specific version
+      docker_layer_caching: true      
+#    docker:
       # using custom image, see .circleci/images/primary/Dockerfile
-      - image: circleci/cci-demo-docker-primary:0.0.2
-      - image: postgres:9.4.1
-        environment:
-          POSTGRES_USER: ubuntu
-          POSTGRES_DB: contacts
-    working_directory: /go/src/github.com/circleci/cci-demo-docker
+#      - image: circleci/cci-demo-docker-primary:0.0.2
+#      - image: postgres:9.4.1
+#        environment:
+#          POSTGRES_USER: ubuntu
+#          POSTGRES_DB: contacts
+#    working_directory: /go/src/github.com/circleci/cci-demo-docker
 
     environment:
       TEST_RESULTS: /tmp/test-results
+    
+    parallelism: 25
 
     steps:
       - checkout
 
-      - run:
-          name: Waiting for Postgres to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for Postgress && exit 1
+#      - run:
+#          name: Waiting for Postgres to be ready
+#          command: |
+#            for i in `seq 1 10`;
+#            do
+#              nc -z localhost 5432 && echo Success && exit 0
+#              echo -n .
+#              sleep 1
+#            done
+#            echo Failed waiting for Postgress && exit 1
 
       - run: mkdir -p $TEST_RESULTS
 
-      - run:
-          name: Run unit tests
-          environment:
-            DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
-            DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
-          command: |
-            set -ou pipefail
-            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
+#      - run:
+#          name: Run unit tests
+#          environment:
+#            DATABASE_URL: "postgres://ubuntu@localhost:5432/contacts?sslmode=disable"
+#            DB_MIGRATIONS: /go/src/github.com/circleci/cci-demo-docker/db/migrations
+#          command: |
+#            set -ou pipefail
+#            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
             # Notice this `set -o pipefail`, this will cause script to fail if `make test` fails
             # without this option script will return success regardless of testing result due to pipe after test command
-            make test | tee ${TEST_RESULTS}/go-test.out
+#            make test | tee ${TEST_RESULTS}/go-test.out
 
-      - setup_remote_docker
+#      - setup_remote_docker
 
       # This should go into custom primary image, here's only for the sake of explanation
       - run:
@@ -51,23 +56,39 @@ jobs:
             VER="17.03.0-ce"
             curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
             tar -xz -C /tmp -f /tmp/docker-$VER.tgz
-            mv /tmp/docker/* /usr/bin
+            sudo mv /tmp/docker/* /usr/bin
+
+      - run:
+          name: Install Docker Compose
+          command: |
+            curl -L https://github.com/docker/compose/releases/download/1.19.0/$
+            chmod +x ~/docker-compose
+            sudo mv ~/docker-compose /usr/local/bin/docker-compose
 
       - run:
           name: Build service
           command: make
 
-      - run:
-          name: Build and push Docker image
-          command: |
-            TAG="0.1.${CIRCLE_BUILD_NUM}"
-            docker build -t circleci/cci-demo-docker:$TAG .
-            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
-            docker push circleci/cci-demo-docker:$TAG
+#      - run:
+#          name: Build and push Docker image
+#          command: |
+#            TAG="0.1.${CIRCLE_BUILD_NUM}"
+#            docker build -t circleci/cci-demo-docker:$TAG .
+#            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
+#            docker push circleci/cci-demo-docker:$TAG
 
-      - store_artifacts:
-          path: /tmp/test-results
-          destination: raw-test-output
+#Persist the specified paths (workspace/echo-output) into the workspace f$
+      - persist_to_workspace:
+          # Must be an absolute path, or relative path from working_directory. $
+          # taken to be the root directory of the workspace.
+          root: /home/circleci/
+          # Must be relative path from root
+          paths:
+            - project
 
-      - store_test_results:
-          path: /tmp/test-results
+#      - store_artifacts:
+#          path: /tmp/test-results
+#          destination: raw-test-output
+
+#      - store_test_results:
+#          path: /tmp/test-results
